### ISSUE TITLE
error on running: graph_extended

### ISSUE THREAD

**Issue by akram1** [OpenSur/Odoo_addons#25]
Odoo8 build 14/3/2015 Linuc 64
All Reporting menu items though an error:

Odoo Client Error
Uncaught ReferenceError: _t is not defined
http://localhost:8069/web/js/web.assets_backend/bb7451e:8357

**Comment by OpenSur** [comment]
Added _lt and _t definitions to addon js, let me know please

**Comment by OpenSur** [comment]
Yes. It was corrected only in branch: 8.0, now is in master also...

**Comment by akram1** [comment]
It works fine now.
